name: "devto-act"
description: "GitHub Actions to publish to dev.to"
inputs:
  skip_generate:
    description: "Skip generation of links"
    required: false
  markdown_files:
    description: "Path to markdown files (space separated) to be submitted"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.markdown_files }}
  env:
    SKIP_GENERATE: ${{ inputs.skip_generate }}
