name: "devto-act"
description: "GitHub Actions to publish to dev.to"
inputs:
  devto_api_key:
    description: "API key for authentication"
    required: false
  skip_generate:
    description: "Skip generation of links"
    required: false
  published:
    description: "Make the article public if non empty"
    required: false
  dry_run:
    description: "Dry run if not empty. Will not send to dev.to"
    required: false
  auto_prefix:
    description: "Generate prefix (cover) image links based on the branch and path to markdown files"
    required: false
  markdown_files:
    description: "Path to markdown files (space separated) to be submitted"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.markdown_files }}
  env:
    DEVTO_API_KEY: ${{ inputs.devto_api_key }}
    SKIP_GENERATE: ${{ inputs.skip_generate }}
    DRY_RUN: ${{ inputs.dry_run }}
    PUBLISHED: ${{ inputs.published }}
    AUTO_PREFIX: ${{ inputs.auto_prefix }}

branding:
  icon: "upload"
  color: "gray-dark"
