name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: devto-act
        uses: ./
        with:
          skip_generate: "true"
